export const OU = [
  {name: 'Clefable', id: '0036', picked: false},
  {name: 'Dugtrio', id: '0051', picked: false},
  {name: 'Gengar', id: '0094', picked: false},
  {name: 'Gyarados', id: '0130', picked: false},
  {name: 'Mew', id: '0151', picked: false},
  {name: 'Tyranitar', id: '0248', picked: false},
  {name: 'Celebi', id: '0251', picked: false},
  {name: 'Weavile', id: '0461', picked: false},
  {name: 'Excadrill', id: '0530', picked: false},
  {name: 'Conkeldurr', id: '0534', picked: false},
  {name: 'Seismitoad', id: '0537', picked: false},
  {name: 'Darmanitan', id: '0555', picked: false},
  {name: 'Ferrothorn', id: '0598', picked: false},
  {name: 'Mandibuzz', id: '0630', picked: false},
  {name: 'Durant', id: '0632', picked: false},
  {name: 'Terrakion', id: '0639', picked: false},
  {name: 'Kyurem', id: '0646', picked: false},
  {name: 'Keldeo', id: '0647', picked: false},
  {name: 'Diggersby', id: '0660', picked: false},
  {name: 'Aegislash', id: '0681', picked: false},
  {name: 'Sylveon', id: '0700', picked: false},
  {name: 'Hawlucha', id: '0701', picked: false},
  {name: 'Toxapex', id: '0748', picked: false},
  {name: 'Mimikyu', id: '0778', picked: false},
  {name: 'Kommo-o', id: '0784', picked: false}
];