export const OU = [
  {name: 'Clefable', id: '0036', picked: false, styles: null},
  {name: 'Dugtrio', id: '0051', picked: false, styles: null},
  {name: 'Gengar', id: '0094', picked: false, styles: null},
  {name: 'Gyarados', id: '0130', picked: false, styles: null},
  {name: 'Mew', id: '0151', picked: false, styles: null},
  {name: 'Tyranitar', id: '0248', picked: false, styles: null},
  {name: 'Celebi', id: '0251', picked: false, styles: null},
  {name: 'Weavile', id: '0461', picked: false, styles: null},
  {name: 'Rotom-Heat', id: '0479h', picked: false, styles: null},
  {name: 'Rotom-Wash', id: '0479w', picked: false, styles: null},
  {name: 'Excadrill', id: '0530', picked: false, styles: null},
  {name: 'Conkeldurr', id: '0534', picked: false, styles: null},
  {name: 'Seismitoad', id: '0537', picked: false, styles: null},
  {name: 'Darmanitan', id: '0555', picked: false, styles: null},
  {name: 'Ferrothorn', id: '0598', picked: false, styles: null},
  {name: 'Bisharp', id: '0625', picked: false, styles: null},
  {name: 'Mandibuzz', id: '0630', picked: false, styles: null},
  {name: 'Durant', id: '0632', picked: false, styles: null},
  {name: 'Hydreigon', id: '0635', picked: false, styles: null},
  {name: 'Terrakion', id: '0639', picked: false, styles: null},
  {name: 'Kyurem', id: '0646', picked: false, styles: null},
  {name: 'Keldeo', id: '0647', picked: false, styles: null},
  {name: 'Diggersby', id: '0660', picked: false, styles: null},
  {name: 'Aegislash', id: '0681', picked: false, styles: null},
  {name: 'Sylveon', id: '0700', picked: false, styles: null},
  {name: 'Hawlucha', id: '0701', picked: false, styles: null},
  {name: 'Toxapex', id: '0748', picked: false, styles: null},
  {name: 'Mimikyu', id: '0778', picked: false, styles: null},
  {name: 'Kommo-o', id: '0784', picked: false, styles: null},
  {name: 'Cinderace', id: '0815', picked: false, styles: null},
  {name: 'Corviknight', id: '0823', picked: false, styles: null},
  {name: 'Toxtricity', id: '0849', picked: false, styles: null},
  {name: 'Hatterene', id: '0858', picked: false, styles: null},
  {name: 'Grimmsnarl', id: '0861', picked: false, styles: null},
  {name: 'Dracovish', id: '0882', picked: false, styles: null},
  {name: 'Dragapult', id: '0887', picked: false, styles: null},
];

export const UU = [
  {name: 'Arcanine', id: '0059', picked: false, styles: null},
  {name: 'Weezing-G', id: '0110g', picked: false, styles: null},
  {name: 'Vaporeon', id: '0134', picked: false, styles: null},
  {name: 'Espeon', id: '0196', picked: false, styles: null},
  {name: 'Umbreon', id: '0197', picked: false, styles: null},
  {name: 'Gardevoir', id: '0282', picked: false, styles: null},
  {name: 'Flygon', id: '0330', picked: false, styles: null},
  {name: 'Roserade', id: '0407', picked: false, styles: null},
  {name: 'Bronzong', id: '0437', picked: false, styles: null},
  {name: 'Lucario', id: '0448', picked: false, styles: null},
  {name: 'Hippowdon', id: '0450', picked: false, styles: null},
  {name: 'Rhyperior', id: '0464', picked: false, styles: null},
  {name: 'Mamoswine', id: '0473', picked: false, styles: null},
  {name: 'Rotom-Mow', id: '0479m', picked: false, styles: null},
  {name: 'Reuniclus', id: '0579', picked: false, styles: null},
  {name: 'Chandelure', id: '0609', picked: false, styles: null},
  {name: 'Haxorus', id: '0612', picked: false, styles: null},
  {name: 'Braviary', id: '0628', picked: false, styles: null},
  {name: 'Doublade', id: '0680', picked: false, styles: null},
  {name: 'Heliolisk', id: '0695', picked: false, styles: null},
  {name: 'Noivern', id: '0715', picked: false, styles: null},
  {name: 'Decidueye', id: '0724', picked: false, styles: null},
  {name: 'Incineroar', id: '0727', picked: false, styles: null},
  {name: 'Primarina', id: '0730', picked: false, styles: null},
  {name: 'Ribombee', id: '0743', picked: false, styles: null},
  {name: 'Araquanid', id: '0752', picked: false, styles: null},
  {name: 'Tsareena', id: '0763', picked: false, styles: null},
  {name: 'Inteleon', id: '0818', picked: false, styles: null},
  {name: 'Coalossal', id: '0839', picked: false, styles: null},
  {name: 'Barraskewda', id: '0847', picked: false, styles: null},
  {name: 'Centiskorch', id: '0851', picked: false, styles: null},
  {name: 'Polteageist', id: '0855', picked: false, styles: null},
  {name: 'Sirfetch\'d', id: '0865', picked: false, styles: null},
  {name: 'Morpeko', id: '0877', picked: false, styles: null},
  {name: 'Copperajah', id: '0879', picked: false, styles: null},
  {name: 'Duraludon', id: '0884', picked: false, styles: null}
];

export const PickBans = [
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'},
  {name: '', id: '0000'}
];